import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Hydration Codex Sidebar Configuration
 * Uses autogenerated sidebars for directories with content
 */
const sidebars: SidebarsConfig = {
  // Reference sidebar - organized by layer (Runtime → SDK → Indexer → UI)
  referenceSidebar: [
    'reference/index',
    {
      type: 'category',
      label: 'Runtime',
      collapsed: false,
      link: {type: 'generated-index', description: 'All runtime pallets'},
      items: [{type: 'autogenerated', dirName: 'reference/pallets'}],
    },
    {
      type: 'category',
      label: 'SDK',
      collapsed: true,
      link: {type: 'generated-index', description: 'All SDK packages'},
      items: [{type: 'autogenerated', dirName: 'reference/sdk'}],
    },
    {
      type: 'category',
      label: 'Indexer',
      collapsed: true,
      link: {type: 'generated-index', description: 'All indexer entities'},
      items: [{type: 'autogenerated', dirName: 'reference/indexer'}],
    },
    {
      type: 'category',
      label: 'UI',
      collapsed: true,
      link: {type: 'generated-index', description: 'All UI hooks'},
      items: [{type: 'autogenerated', dirName: 'reference/hooks'}],
    },
  ],

  // AI & Agents sidebar
  aiSidebar: [
    'ai/index',
    {
      type: 'category',
      label: 'Context Files (Markdown)',
      collapsed: false,
      items: [
        'ai/context/omniscience',
        'ai/context/l1-runtime',
        'ai/context/l2-sdk',
        'ai/context/l3-indexer',
        'ai/context/l4-ui',
      ],
    },
    {
      type: 'category',
      label: 'Data Files (JSON)',
      collapsed: false,
      items: [
        'ai/context/data-files',
      ],
    },
  ],
};

export default sidebars;
