/**
 * Indexer Entity Documentation Synthesizer
 *
 * Generates MDX documentation pages for GraphQL entities from the indexer.
 *
 * Features:
 * - Schema and TypeScript interface for each entity
 * - Source handlers table linking runtime events to handler functions
 * - Links to GitHub source files with line numbers
 * - Cross-references to runtime pallets
 * - Example GraphQL queries
 *
 * Handler Extraction (from extract/indexer.ts):
 * - Uses TypeScript static analysis (ts-morph) to trace event handlers
 * - Finds getSectionByEventName() calls and traces to the actual handler function
 * - Extracts file path and line number for direct GitHub links
 *
 * Output: docs-site/docs/reference/indexer/*.mdx
 */

import { join } from 'path';
import { existsSync, mkdirSync, writeFileSync, readdirSync, statSync, readFileSync } from 'fs';
import { createLogger } from '../utils/logger.js';
import { readJSON } from '../utils/files.js';
import { normalizePalletName } from '../utils/pallets.js';
import type { CanonicalIndex } from '../schemas/canonical-ids.js';
import { parseCanonicalId } from '../schemas/canonical-ids.js';

const log = createLogger('indexer');

// =============================================================================
// HOOK INDEX (loaded from hooks synthesizer output)
// =============================================================================

// Cache for hook index
let hookIndexCache: Record<string, { category: string; file: string }> | null = null;

/**
 * Load hook index generated by hooks synthesizer.
 */
function loadHookIndex(outputPath: string): Record<string, { category: string; file: string }> {
  if (hookIndexCache) return hookIndexCache;

  const indexPath = join(outputPath, '../static/hook-index.json');
  if (existsSync(indexPath)) {
    try {
      const content = readFileSync(indexPath, 'utf-8');
      hookIndexCache = JSON.parse(content);
      log.info(`Loaded hook index: ${Object.keys(hookIndexCache!).length} hooks`);
      return hookIndexCache!;
    } catch {
      log.warn('Failed to load hook index');
    }
  }

  hookIndexCache = {};
  return hookIndexCache;
}

/**
 * Get hook category from index.
 */
function getHookCategory(hookName: string, hookIndex: Record<string, { category: string; file: string }>): string | null {
  return hookIndex[hookName]?.category ?? null;
}

interface IndexerExtraction {
  meta: {
    layer: string;
    name: string;
    extractedAt: string;
    source: {
      commit: string;
      branch: string;
      repo: string;
    };
  };
  schema: {
    entities: IndexerEntity[];
  };
  endpoints?: {
    production: string;
    testnet?: string;
  };
  handlers?: EventHandler[];
  runtimeEvents?: string[];
  eventToHandlerMap?: Record<string, { handlers: string[]; entities: string[] }>;
}

interface IndexerEntity {
  name: string;
  fields: EntityField[];
}

interface EntityField {
  name: string;
  type: string;
  nullable: boolean;
}

interface EventHandler {
  event: string;
  handler: string;
  file: string;
  line: number;
  createsEntities?: string[];
}

interface EntitySourceInfo {
  runtimeEvent: string;
  handlers: string[];
}

interface HandlerInfo {
  file: string;
  line: number;
}

interface IndexerOptions {
  extractionsPath: string;
  outputPath: string;
}

// Core entities (DeFi-related)
const PRIORITY_ENTITIES = [
  'Asset',
  'Pool',
  'OmnipoolAsset',
  'StablepoolAsset',
  'XYKPoolAsset',
  'LBPPoolAsset',
  'Trade',
  'Swap',
  'Transfer',
  'LiquidityChange',
  'Stake',
  'DcaOrder',
  'DcaExecution',
];

export async function synthesizeIndexer(options: IndexerOptions): Promise<void> {
  const { extractionsPath, outputPath } = options;

  log.section('Indexer Documentation Generation');

  // Load indexer extraction
  const extraction = loadLatestExtraction(extractionsPath);
  if (!extraction) {
    throw new Error('Missing indexer extraction. Run npm run extract:indexer first.');
  }

  const entities = extraction.schema.entities;
  log.info(`Loaded ${entities.length} entities`);
  log.info(`Source: ${extraction.meta.source.repo}@${extraction.meta.source.branch}`);

  // Load cross-reference index for bi-directional links (v2 with canonical IDs)
  const crossRefPath = join(outputPath, '../static/cross-references.json');
  let crossRef: CanonicalIndex | null = null;
  if (existsSync(crossRefPath)) {
    crossRef = readJSON<CanonicalIndex>(crossRefPath);
    const totalEdges = crossRef?.edges?.length ?? 0;
    log.info(`Loaded cross-reference index: ${totalEdges} edges`);
  } else {
    log.warn('Cross-reference index not found. Run npm run synthesize:crossref first.');
  }

  // Load hook index for accurate category mapping
  const hookIndex = loadHookIndex(outputPath);

  // Build entity → related maps from edges
  const entityToHooks = new Map<string, { name: string; category: string }[]>();
  const entityToPallets = new Map<string, string[]>();

  if (crossRef?.edges) {
    for (const edge of crossRef.edges) {
      if (edge.type === 'contains') continue;

      try {
        const fromParsed = parseCanonicalId(edge.from);
        const toParsed = parseCanonicalId(edge.to);

        // UI hook → Indexer entity (reverse direction: entity is queried by hook)
        if (fromParsed.layer === 'ui' && fromParsed.segments[0]?.type === 'hook' &&
            toParsed.layer === 'indexer' && toParsed.segments[0]?.type === 'entity') {
          const entityName = toParsed.segments[0].name;
          const hookName = fromParsed.segments[0].name;

          // Only include hooks that exist in the hook index (have generated pages)
          const category = getHookCategory(hookName, hookIndex);
          if (!category) continue; // Skip hooks without generated pages

          if (!entityToHooks.has(entityName)) entityToHooks.set(entityName, []);
          const hooks = entityToHooks.get(entityName)!;
          if (!hooks.some(h => h.name === hookName)) {
            hooks.push({ name: hookName, category });
          }
        }

        // Indexer entity → Runtime pallet
        if (fromParsed.layer === 'indexer' && fromParsed.segments[0]?.type === 'entity' &&
            toParsed.layer === 'runtime') {
          const entityName = fromParsed.segments[0].name;
          const palletName = toParsed.segments[0].name;

          if (!entityToPallets.has(entityName)) entityToPallets.set(entityName, []);
          const pallets = entityToPallets.get(entityName)!;
          if (!pallets.includes(palletName)) pallets.push(palletName);
        }
      } catch {
        continue;
      }
    }
  }

  log.info(`Loaded ${entityToHooks.size} entity→UI mappings, ${entityToPallets.size} entity→Runtime mappings`);

  // Build entity → source handlers mapping from eventToHandlerMap
  const entityToSources = new Map<string, EntitySourceInfo[]>();
  if (extraction.eventToHandlerMap) {
    for (const [runtimeEvent, mapping] of Object.entries(extraction.eventToHandlerMap)) {
      for (const entity of mapping.entities) {
        if (!entityToSources.has(entity)) entityToSources.set(entity, []);
        const sources = entityToSources.get(entity)!;
        // Check if this event is already added
        if (!sources.some(s => s.runtimeEvent === runtimeEvent)) {
          sources.push({
            runtimeEvent,
            handlers: mapping.handlers,
          });
        }
      }
    }
    log.info(`Built entity→source mappings for ${entityToSources.size} entities`);
  }

  // Build handler info map for GitHub links
  const handlerInfoMap = new Map<string, HandlerInfo>();
  if (extraction.handlers) {
    for (const h of extraction.handlers) {
      handlerInfoMap.set(h.handler, { file: h.file, line: h.line });
    }
    log.info(`Built handler info map: ${handlerInfoMap.size} handlers`);
  }

  // Create output directory
  const indexerOutputPath = join(outputPath, 'reference/indexer');
  mkdirSync(indexerOutputPath, { recursive: true });

  // Sort entities: priority first, then alphabetically
  const sortedEntities = [...entities].sort((a, b) => {
    const aIdx = PRIORITY_ENTITIES.indexOf(a.name);
    const bIdx = PRIORITY_ENTITIES.indexOf(b.name);
    if (aIdx !== -1 && bIdx !== -1) return aIdx - bIdx;
    if (aIdx !== -1) return -1;
    if (bIdx !== -1) return 1;
    return a.name.localeCompare(b.name);
  });

  log.section('Generating Entity Pages');

  let generatedCount = 0;

  const graphqlEndpoint = extraction.endpoints?.production || 'https://galacticcouncil.squids.live/hydration-pools:unified-prod/api/graphql';

  for (const entity of sortedEntities) {
    const hooks = entityToHooks.get(entity.name) || [];
    const pallets = entityToPallets.get(entity.name) || [];
    const sources = entityToSources.get(entity.name) || [];
    const mdxContent = generateEntityMdx(entity, extraction.meta, hooks, pallets, sources, graphqlEndpoint, handlerInfoMap);
    const filePath = join(indexerOutputPath, `${entity.name}.mdx`);
    writeFileSync(filePath, mdxContent);
    generatedCount++;
  }

  log.info(`Generated ${generatedCount} entity pages`);

  // Index page is auto-generated by Docusaurus sidebar (generated-index)

  log.success(`Generated ${generatedCount} indexer pages`);

  log.section('Generation Complete');
  console.log(`\n  Output: ${indexerOutputPath}/`);
  console.log(`  Pages: ${generatedCount}\n`);
}

function loadLatestExtraction(baseDir: string): IndexerExtraction | null {
  const layerDir = join(baseDir, 'indexer');
  if (!existsSync(layerDir)) return null;

  // Try extraction.json first (newest extraction format)
  const extractionPath = join(layerDir, 'extraction.json');
  if (existsSync(extractionPath)) {
    const content = readFileSync(extractionPath, 'utf-8');
    return JSON.parse(content);
  }

  // Try 'latest' symlink
  const latestPath = join(layerDir, 'latest');
  if (existsSync(latestPath)) {
    const content = readFileSync(latestPath, 'utf-8');
    return JSON.parse(content);
  }

  // Otherwise find newest JSON file
  const files = readdirSync(layerDir).filter(f => f.endsWith('.json') && f !== 'extraction.json');
  if (files.length === 0) return null;

  const sortedFiles = files.sort((a, b) => {
    const statA = statSync(join(layerDir, a));
    const statB = statSync(join(layerDir, b));
    return statB.mtime.getTime() - statA.mtime.getTime();
  });

  const content = readFileSync(join(layerDir, sortedFiles[0]), 'utf-8');
  return JSON.parse(content);
}

function mapGraphQLType(type: string): string {
  // Map GraphQL types to TypeScript-like types
  const typeMap: Record<string, string> = {
    'ID': 'string',
    'String': 'string',
    'Int': 'number',
    'Float': 'number',
    'Boolean': 'boolean',
    'BigInt': 'bigint',
    'DateTime': 'Date',
    'JSON': 'object',
    'Bytes': 'Uint8Array',
  };
  return typeMap[type] || type;
}

function generateEntityMdx(
  entity: IndexerEntity,
  meta: IndexerExtraction['meta'],
  hooks: { name: string; category: string }[],
  pallets: string[],
  sources: EntitySourceInfo[],
  graphqlEndpoint: string,
  handlerInfoMap: Map<string, HandlerInfo>
): string {
  const entityFileName = entity.name.charAt(0).toLowerCase() + entity.name.slice(1);
  const githubLink = `https://github.com/${meta.source.repo}/blob/${meta.source.commit}/indexers/liquidity-pools/src/model/generated/${entityFileName}.model.ts`;

  // Categorize fields
  const idFields = entity.fields.filter(f => f.type === 'ID');
  const dataFields = entity.fields.filter(f => f.type !== 'ID' && !f.name.endsWith('Id'));
  const relationFields = entity.fields.filter(f => f.name.endsWith('Id') && f.type !== 'ID');

  const lines: string[] = [
    '---',
    `title: ${entity.name}`,
    `description: Indexer entity documentation`,
    `sidebar_label: ${entity.name}`,
    '---',
    '',
    `# ${entity.name}`,
    '',
    '<!-- AI_DESCRIPTION_START -->',
    '> **TODO**: AI-generated description of what this entity represents.',
    '<!-- AI_DESCRIPTION_END -->',
    '',
    `| Property | Value |`,
    `|----------|-------|`,
    `| Fields | ${entity.fields.length} |`,
    `| Nullable Fields | ${entity.fields.filter(f => f.nullable).length} |`,
    '',
    `**Links:** [GitHub](${githubLink}) | [GraphQL Playground](${graphqlEndpoint})`,
    '',
    '## Schema',
    '',
    '```graphql',
    `type ${entity.name} {`,
  ];

  for (const field of entity.fields) {
    const nullMark = field.nullable ? '' : '!';
    lines.push(`  ${field.name}: ${field.type}${nullMark}`);
  }

  lines.push('}');
  lines.push('```');
  lines.push('');

  // TypeScript interface
  lines.push('## TypeScript Interface');
  lines.push('');
  lines.push('```typescript');
  lines.push(`interface ${entity.name} {`);

  for (const field of entity.fields) {
    const tsType = mapGraphQLType(field.type);
    const nullMark = field.nullable ? ' | null' : '';
    lines.push(`  ${field.name}: ${tsType}${nullMark};`);
  }

  lines.push('}');
  lines.push('```');
  lines.push('');

  // Source Handlers section - shows which runtime events populate this entity
  if (sources.length > 0) {
    lines.push('## Source Handlers');
    lines.push('');
    lines.push('This entity is populated by the following runtime events and handlers:');
    lines.push('');
    lines.push('| Runtime Event | Handler |');
    lines.push('|---------------|---------|');

    for (const source of sources) {
      const [pallet, event] = source.runtimeEvent.split('.');

      // Create GitHub links for handlers
      const handlerLinks: string[] = [];

      for (const h of source.handlers) {
        const info = handlerInfoMap.get(h);
        if (info) {
          const githubUrl = `https://github.com/${meta.source.repo}/blob/${meta.source.commit}/${info.file}#L${info.line}`;
          handlerLinks.push(`[\`${h}\`](${githubUrl})`);
        } else {
          handlerLinks.push(`\`${h}\``);
        }
      }

      const handlersStr = handlerLinks.length > 0 ? handlerLinks.join(', ') : '-';

      // Link runtime event to pallet docs (normalize pallet name for correct URL)
      const normalizedPallet = normalizePalletName(pallet);
      const palletLink = `/reference/pallets/${normalizedPallet}`;
      const eventLink = `${palletLink}#${event?.toLowerCase() || ''}`;
      lines.push(`| [${source.runtimeEvent}](${eventLink}) | ${handlersStr} |`);
    }

    lines.push('');
  }

  // Example query
  lines.push('## Example Query');
  lines.push('');
  lines.push('```graphql');
  lines.push(`query Get${entity.name}s {`);
  lines.push(`  ${entity.name.charAt(0).toLowerCase() + entity.name.slice(1)}s(limit: 10) {`);
  for (const field of entity.fields.slice(0, 5)) {
    lines.push(`    ${field.name}`);
  }
  if (entity.fields.length > 5) {
    lines.push('    # ... more fields');
  }
  lines.push('  }');
  lines.push('}');
  lines.push('```');
  lines.push('');

  // References section (cross-references to other layers)
  if (pallets.length > 0 || hooks.length > 0) {
    lines.push('## References');
    lines.push('');

    // Runtime pallets this entity tracks
    if (pallets.length > 0) {
      lines.push(`### Runtime (${pallets.length})`);
      lines.push('');
      for (const pallet of pallets) {
        lines.push(`- [${pallet}](/reference/pallets/${pallet})`);
      }
      lines.push('');
    }

    // UI hooks that query this entity
    if (hooks.length > 0) {
      lines.push(`### UI (${hooks.length})`);
      lines.push('');
      for (const hook of hooks) {
        lines.push(`- [${hook.name}](/reference/hooks/${hook.category}/${hook.name})`);
      }
      lines.push('');
    }
  }

  return lines.join('\n');
}

function generateIndexerIndex(
  extraction: IndexerExtraction,
  entities: IndexerEntity[],
  entityToHooks: Map<string, { name: string; category: string }[]>
): string {
  const totalFields = entities.reduce((sum, e) => sum + e.fields.length, 0);

  const lines: string[] = [
    '---',
    'title: Indexer Reference',
    'description: Complete reference for indexer entities and queries',
    'sidebar_class_name: hidden',
    '---',
    '',
    '# Indexer Reference',
    '',
    `Documentation for ${entities.length} GraphQL entities.`,
    '',
    `**Source:** [${extraction.meta.source.repo}](https://github.com/${extraction.meta.source.repo})`,
    `**GraphQL Playground:** [Open Playground](${extraction.endpoints?.production || 'https://galacticcouncil.squids.live/hydration-pools:unified-prod/api/graphiql'})`,
    '',
    '## Core Entities',
    '',
    '| Entity | Fields | UI Hooks |',
    '|--------|--------|----------|',
  ];

  const coreEntities = entities.filter(e => PRIORITY_ENTITIES.includes(e.name));
  for (const entity of coreEntities) {
    const hooksCount = entityToHooks.get(entity.name)?.length || 0;
    const hooksInfo = hooksCount > 0 ? `${hooksCount}` : '-';
    lines.push(`| [${entity.name}](/reference/indexer/${entity.name}) | ${entity.fields.length} | ${hooksInfo} |`);
  }

  lines.push('');
  lines.push('## All Entities');
  lines.push('');
  lines.push('| Entity | Fields | UI |');
  lines.push('|--------|--------|----|');

  const otherEntities = entities.filter(e => !PRIORITY_ENTITIES.includes(e.name));
  for (const entity of otherEntities) {
    const hooksCount = entityToHooks.get(entity.name)?.length || 0;
    const hooksInfo = hooksCount > 0 ? `${hooksCount}` : '-';
    lines.push(`| [${entity.name}](/reference/indexer/${entity.name}) | ${entity.fields.length} | ${hooksInfo} |`);
  }

  lines.push('');

  return lines.join('\n');
}

// CLI
if (import.meta.url === `file://${process.argv[1]}`) {
  const extractionsPath = process.env.EXTRACTIONS_PATH || './raw';
  const outputPath = process.env.OUTPUT_PATH || './docs-site/docs';

  synthesizeIndexer({
    extractionsPath,
    outputPath,
  }).catch((err) => {
    console.error('Indexer generation failed:', err);
    process.exit(1);
  });
}
