/**
 * Pallet Documentation Synthesizer
 *
 * Generates comprehensive MDX documentation pages for all runtime pallets.
 *
 * Features:
 * - Extracts docs from README.md and lib.rs doc comments (//!)
 * - Fetches external pallet docs from GitHub (Polkadot SDK, ORML, Hyperbridge, Frontier)
 * - Parses Cargo.lock to find pallet sources and exact paths via [workspace.dependencies]
 * - Cross-references events with indexer entities ("Indexed by" links)
 * - Links to GitHub, docs.rs, crates.io, and Subscan
 *
 * Documentation Sources:
 * - HydraDX pallets: Read from local repos/hydration-node/pallets/
 * - External pallets: Fetched from GitHub using raw.githubusercontent.com
 *
 * Output: docs-site/docs/reference/pallets/*.mdx
 */

import { join } from 'path';
import { existsSync, mkdirSync, writeFileSync, readdirSync, statSync, readFileSync } from 'fs';
import { execSync } from 'child_process';
import { createLogger } from '../utils/logger.js';
import { readJSON } from '../utils/files.js';
import type { CanonicalIndex, CanonicalEntry } from '../schemas/canonical-ids.js';
import { parseCanonicalId, runtime } from '../schemas/canonical-ids.js';

// Base path to HydraDX-node submodule
const HYDRADX_NODE_PATH = './repos/hydration-node';

// =============================================================================
// HOOK INDEX (loaded from hooks synthesizer output)
// =============================================================================

// Cache for hook index
let hookIndexCache: Record<string, { category: string; file: string }> | null = null;

/**
 * Load hook index generated by hooks synthesizer.
 * Falls back to 'utils' if hook not found.
 */
function loadHookIndex(outputPath: string): Record<string, { category: string; file: string }> {
  if (hookIndexCache) return hookIndexCache;

  const indexPath = join(outputPath, '../static/hook-index.json');
  if (existsSync(indexPath)) {
    try {
      const content = readFileSync(indexPath, 'utf-8');
      hookIndexCache = JSON.parse(content);
      log.info(`Loaded hook index: ${Object.keys(hookIndexCache!).length} hooks`);
      return hookIndexCache!;
    } catch {
      log.warn('Failed to load hook index, using fallback');
    }
  } else {
    log.warn('Hook index not found. Run npm run synthesize:hooks first.');
  }

  hookIndexCache = {};
  return hookIndexCache;
}

/**
 * Get hook category from index, or return null if not found.
 */
function getHookCategory(hookName: string, hookIndex: Record<string, { category: string; file: string }>): string | null {
  return hookIndex[hookName]?.category ?? null;
}

// Pallet runtime info from construct_runtime!
interface PalletRuntimeInfo {
  crateName: string;       // e.g., "pallet-collective"
  instance?: string;       // e.g., "Instance2" if using an instance
  index: number;           // Pallet index in runtime
}

// Cache for pallet-to-crate mapping from construct_runtime!
let palletToCrateCache: Map<string, PalletRuntimeInfo> | null = null;

// Parse construct_runtime! macro to get pallet name -> crate name + instance mapping
function parsePalletToCrateMapping(): Map<string, PalletRuntimeInfo> {
  if (palletToCrateCache) return palletToCrateCache;

  palletToCrateCache = new Map();
  const runtimePath = join(HYDRADX_NODE_PATH, 'runtime/hydradx/src/lib.rs');

  if (!existsSync(runtimePath)) {
    log.warn('Runtime lib.rs not found, pallet mapping unavailable');
    return palletToCrateCache;
  }

  try {
    const content = readFileSync(runtimePath, 'utf-8');

    // Find construct_runtime! macro content
    const match = content.match(/construct_runtime!\s*\(\s*pub\s+enum\s+Runtime\s*\{([\s\S]*?)\}\s*\)/);
    if (!match) {
      log.warn('construct_runtime! macro not found');
      return palletToCrateCache;
    }

    const runtimeBlock = match[1];

    // Parse each line: "PalletName: crate_path::<Instance> = index"
    // Examples:
    //   System: frame_system exclude_parts { Origin } = 1,
    //   Balances: pallet_balances = 7,
    //   TechnicalCommittee: pallet_collective::<Instance2> = 25,
    //   OmnipoolWarehouseLM: warehouse_liquidity_mining::<Instance1> = 62,
    //   Origins: pallet_custom_origins = 38,
    const palletRegex = /^\s*(\w+):\s*([\w_]+)(?:::<(\w+)>)?(?:\s+exclude_parts\s*\{[^}]*\})?\s*=\s*(\d+)/gm;

    let palletMatch;
    while ((palletMatch = palletRegex.exec(runtimeBlock)) !== null) {
      const palletName = palletMatch[1];
      const cratePath = palletMatch[2];
      const instance = palletMatch[3];  // undefined if no instance
      const index = parseInt(palletMatch[4], 10);

      // Convert underscore to hyphen for crate name lookup
      // frame_system -> frame-system, pallet_balances -> pallet-balances
      const crateName = cratePath.replace(/_/g, '-');

      palletToCrateCache.set(palletName.toLowerCase(), {
        crateName,
        instance,
        index,
      });
    }

    log.info(`Parsed ${palletToCrateCache.size} pallet-to-crate mappings from construct_runtime!`);
  } catch (err) {
    log.warn(`Failed to parse construct_runtime!: ${err}`);
  }

  return palletToCrateCache;
}

// Get just the crate name for a pallet (for backward compatibility)
function getCrateNameForPallet(palletName: string): string | undefined {
  const info = parsePalletToCrateMapping().get(palletName.toLowerCase());
  return info?.crateName;
}

// Cache for HydraDX-node git info
let hydradxGitInfo: { commit: string; branch: string } | null = null;

// Get HydraDX-node git commit and branch from the actual submodule
function getHydradxGitInfo(): { commit: string; branch: string } {
  if (hydradxGitInfo) return hydradxGitInfo;

  try {
    const commit = execSync('git rev-parse HEAD', {
      cwd: HYDRADX_NODE_PATH,
      encoding: 'utf-8',
    }).trim();

    // Get branch name (may be detached HEAD, so fallback to commit)
    let branch = 'master';
    try {
      branch = execSync('git rev-parse --abbrev-ref HEAD', {
        cwd: HYDRADX_NODE_PATH,
        encoding: 'utf-8',
      }).trim();
      if (branch === 'HEAD') {
        // Detached HEAD, try to get tag or use commit
        branch = execSync('git describe --tags --exact-match 2>/dev/null || echo ""', {
          cwd: HYDRADX_NODE_PATH,
          encoding: 'utf-8',
        }).trim() || commit.substring(0, 8);
      }
    } catch {
      branch = commit.substring(0, 8);
    }

    hydradxGitInfo = { commit, branch };
    return hydradxGitInfo;
  } catch (err) {
    // Fallback if git command fails
    hydradxGitInfo = { commit: 'master', branch: 'master' };
    return hydradxGitInfo;
  }
}

const log = createLogger('pallets');

// Detailed metadata format (from metadata.json)
interface DetailedMetadata {
  specName: string;
  specVersion: number;
  implVersion: number;
  blockNumber: number;
  blockHash: string;
  extractedAt: string;
  pallets: DetailedPalletMetadata[];
}

interface DetailedPalletMetadata {
  name: string;
  index: number;
  storage: StorageItem[];
  calls: CallItem[];
  events: EventItem[];
  constants: ConstantItem[];
}

interface StorageItem {
  name: string;
  modifier: string;
  type: string;
  keyType?: string;
  valueType: string;
  docs: string;
}

interface CallItem {
  name: string;
  index: number;
  args: { name: string; type: string }[];
  docs: string;
}

interface EventItem {
  name: string;
  fields: { name?: string; type: string }[];
  docs: string;
}

interface ConstantItem {
  name: string;
  type: string;
  value: string;
  docs: string;
}

// Simplified metadata format (from baseline.json - fallback)
interface ChainMetadata {
  extractedAt: string;
  source: string;
  endpoint: string;
  specName: string;
  specVersion: number;
  blockNumber: number;
  pallets: PalletMetadata[];
}

interface PalletMetadata {
  name: string;
  index: number;
  calls: string[];
  events: string[];
  storage: string[];
  constants: string[];
}

interface PalletsOptions {
  extractionsPath: string;
  outputPath: string;
}


export async function synthesizePallets(options: PalletsOptions): Promise<void> {
  const { extractionsPath, outputPath } = options;

  log.section('Pallet Documentation Generation');

  // Load detailed metadata (preferred) or fall back to baseline
  const detailedPath = join(extractionsPath, 'metadata/metadata.json');
  const baselinePath = join(extractionsPath, 'metadata/baseline.json');

  let detailedMetadata: DetailedMetadata | null = null;
  let metadata: ChainMetadata;

  if (existsSync(detailedPath)) {
    const loadedMetadata = readJSON<DetailedMetadata>(detailedPath);
    if (!loadedMetadata) {
      throw new Error('Failed to load detailed metadata.');
    }
    detailedMetadata = loadedMetadata;
    log.info(`Loaded detailed metadata: ${loadedMetadata.pallets.length} pallets with types`);
    // Create compatible ChainMetadata for legacy functions
    metadata = {
      extractedAt: loadedMetadata.extractedAt,
      source: 'hydradx',
      endpoint: '',
      specName: loadedMetadata.specName,
      specVersion: loadedMetadata.specVersion,
      blockNumber: loadedMetadata.blockNumber,
      pallets: loadedMetadata.pallets.map(p => ({
        name: p.name,
        index: p.index,
        calls: p.calls.map(c => c.name),
        events: p.events.map(e => e.name),
        storage: p.storage.map(s => s.name),
        constants: p.constants.map(c => c.name),
      })),
    };
  } else if (existsSync(baselinePath)) {
    const loadedMetadata = readJSON<ChainMetadata>(baselinePath);
    if (!loadedMetadata) {
      throw new Error('Failed to load baseline metadata.');
    }
    metadata = loadedMetadata;
    log.warn('Using baseline metadata (no types). Run npm run extract:metadata for detailed types.');
  } else {
    throw new Error('Missing chain metadata. Run npm run extract:chain:baseline first.');
  }

  log.info(`Spec: ${metadata.specName} v${metadata.specVersion}`);

  // Load cross-reference index (v2 with canonical IDs)
  const crossRefPath = join(process.env.OUTPUT_PATH || './docs-site/docs', '../static/cross-references.json');
  let crossRef: CanonicalIndex | null = null;
  if (existsSync(crossRefPath)) {
    crossRef = readJSON<CanonicalIndex>(crossRefPath);
    const totalEdges = crossRef?.edges?.length ?? 0;
    log.info(`Loaded cross-reference index: ${totalEdges} edges`);
  } else {
    log.warn('Cross-reference index not found. Run npm run synthesize:crossref first.');
  }

  // Load hook index for accurate category mapping
  const hookIndex = loadHookIndex(outputPath);

  // Load SDK extraction to find SDK methods that use each pallet/storage
  interface SDKMethodRef { package: string; method: string; }
  const palletToSDK = new Map<string, SDKMethodRef[]>();
  // Map: "pallet.storage_item" → [{method, package}]
  interface StorageMethodRef { method: string; package: string; }
  const storageToSDK = new Map<string, StorageMethodRef[]>();

  // Try enhanced extraction first, then fall back to regular
  const enhancedPath = join(extractionsPath, 'sdk/extraction-enhanced.json');
  const regularPath = join(extractionsPath, 'sdk/extraction.json');
  const sdkExtractionPath = existsSync(enhancedPath) ? enhancedPath : regularPath;

  if (existsSync(sdkExtractionPath)) {
    try {
      const sdkExtraction = readJSON<{
        packages: Array<{
          name: string;
          palletCalls?: {
            tx: Array<{ pallet: string; item: string; methods: string[] }>;
            query: Array<{ pallet: string; item: string; methods: string[] }>;
            consts: Array<{ pallet: string; item: string; methods: string[] }>;
          };
        }>;
      }>(sdkExtractionPath);
      if (sdkExtraction?.packages) {
        for (const pkg of sdkExtraction.packages) {
          if (!pkg.palletCalls) continue;
          const shortPkgName = pkg.name.replace('@galacticcouncil/', '');

          // Process all call types
          const allCalls = [
            ...(pkg.palletCalls.tx || []),
            ...(pkg.palletCalls.query || []),
            ...(pkg.palletCalls.consts || []),
          ];

          for (const call of allCalls) {
            const palletName = call.pallet.toLowerCase();

            // Pallet-level mapping
            if (!palletToSDK.has(palletName)) palletToSDK.set(palletName, []);
            const refs = palletToSDK.get(palletName)!;
            if (!refs.some(r => r.package === shortPkgName)) {
              refs.push({ package: shortPkgName, method: call.item });
            }

            // Storage-level mapping with package info for linking
            if (call.item && call.methods) {
              const storageKey = `${palletName}.${call.item.toLowerCase()}`;
              if (!storageToSDK.has(storageKey)) storageToSDK.set(storageKey, []);
              const storageMethods = storageToSDK.get(storageKey)!;
              for (const method of call.methods) {
                if (!storageMethods.some(m => m.method === method)) {
                  storageMethods.push({ method, package: shortPkgName });
                }
              }
            }
          }
        }
        log.info(`Loaded SDK→Pallet mappings: ${palletToSDK.size} pallets, ${storageToSDK.size} storage items`);
      }
    } catch {
      log.warn('Failed to load SDK extraction');
    }
  }

  // Load handler details and event→entity mappings from indexer extraction
  interface HandlerInfo { event: string; file: string; line: number; }
  const handlerIndex = new Map<string, HandlerInfo>();
  let indexerSource: { repo: string; commit: string } | null = null;
  let eventToHandlerMap: Record<string, { handlers: string[]; entities: string[] }> = {};
  const validEntityNames = new Set<string>(); // Track valid entity names (not enum types)
  const indexerExtractionPath = join(extractionsPath, 'indexer/extraction.json');
  if (existsSync(indexerExtractionPath)) {
    try {
      const indexerExtraction = readJSON<{
        meta: { source: { repo: string; commit: string } };
        schema?: { entities: { name: string }[] };
        handlers: { handler: string; event: string; file: string; line: number }[];
        eventToHandlerMap?: Record<string, { handlers: string[]; entities: string[] }>;
      }>(indexerExtractionPath);
      if (indexerExtraction?.meta?.source) {
        indexerSource = indexerExtraction.meta.source;
      }
      // Load valid entity names from schema
      if (indexerExtraction?.schema?.entities) {
        for (const entity of indexerExtraction.schema.entities) {
          validEntityNames.add(entity.name);
        }
        log.info(`Loaded ${validEntityNames.size} valid entity names`);
      }
      if (indexerExtraction?.handlers) {
        for (const h of indexerExtraction.handlers) {
          handlerIndex.set(h.handler, { event: h.event, file: h.file, line: h.line });
        }
        log.info(`Loaded handler index: ${handlerIndex.size} handlers`);
      }
      if (indexerExtraction?.eventToHandlerMap) {
        eventToHandlerMap = indexerExtraction.eventToHandlerMap;
        log.info(`Loaded event→entity map: ${Object.keys(eventToHandlerMap).length} events`);
      }
    } catch {
      log.warn('Failed to load indexer extraction');
    }
  }

  // Build pallet lookup maps from cross-ref edges
  const palletToHooks = new Map<string, { name: string; category: string }[]>();
  const palletToEntities = new Map<string, string[]>();

  if (crossRef?.edges) {
    const palletHooksMap = new Map<string, Map<string, { name: string; category: string }>>();
    const palletEntitiesMap = new Map<string, Set<string>>();

    for (const edge of crossRef.edges) {
      if (edge.type === 'contains') continue;

      try {
        const fromParsed = parseCanonicalId(edge.from);
        const toParsed = parseCanonicalId(edge.to);

        // UI hook → Runtime (get pallet name from target)
        if (fromParsed.layer === 'ui' && fromParsed.segments[0]?.type === 'hook' &&
            toParsed.layer === 'runtime') {
          const palletName = toParsed.segments[0].name.toLowerCase();
          const hookName = fromParsed.segments[0].name;

          // Only include hooks that exist in the hook index (have generated pages)
          const category = getHookCategory(hookName, hookIndex);
          if (!category) continue; // Skip hooks without generated pages

          if (!palletHooksMap.has(palletName)) palletHooksMap.set(palletName, new Map());
          palletHooksMap.get(palletName)!.set(hookName, { name: hookName, category });
        }

        // Indexer entity → Runtime pallet
        if (fromParsed.layer === 'indexer' && fromParsed.segments[0]?.type === 'entity' &&
            toParsed.layer === 'runtime' && toParsed.segments[0]?.type === 'pallet') {
          const palletName = toParsed.segments[0].name.toLowerCase();
          const entityName = fromParsed.segments[0].name;

          if (!palletEntitiesMap.has(palletName)) palletEntitiesMap.set(palletName, new Set());
          palletEntitiesMap.get(palletName)!.add(entityName);
        }

        // Indexer handler → Runtime event (handler handles pallet event)
        if (fromParsed.layer === 'indexer' && fromParsed.segments[0]?.type === 'handler' &&
            toParsed.layer === 'runtime' && edge.type === 'handles') {
          const palletName = toParsed.segments[0].name.toLowerCase();
          // Use the handler name as a proxy for entities (handlers often create/update entities)
          const handlerName = fromParsed.segments[0].name;

          if (!palletEntitiesMap.has(palletName)) palletEntitiesMap.set(palletName, new Set());
          // Add a marker like "via handleAssetRegistryRegistered" to show the handler
          palletEntitiesMap.get(palletName)!.add(`handler:${handlerName}`);
        }
      } catch {
        continue;
      }
    }

    // Convert to final format
    for (const [pallet, hooksMap] of palletHooksMap) {
      if (hooksMap.size > 0) {
        palletToHooks.set(pallet, Array.from(hooksMap.values()));
      }
    }
    for (const [pallet, entitiesSet] of palletEntitiesMap) {
      if (entitiesSet.size > 0) {
        palletToEntities.set(pallet, Array.from(entitiesSet));
      }
    }
  }
  log.info(`Loaded ${palletToHooks.size} pallet→UI mappings, ${palletToEntities.size} pallet→Indexer mappings`);

  // Pre-fetch workspace Cargo.toml files to find exact crate paths
  await prefetchWorkspaceMembers();

  // Create output directory
  const palletsOutputPath = join(outputPath, 'reference/pallets');
  mkdirSync(palletsOutputPath, { recursive: true });

  // Sort pallets by index
  const allPallets = [...metadata.pallets].sort((a, b) => a.index - b.index);

  // Pre-fetch docs for external pallets from GitHub
  await prefetchExternalPalletDocs(allPallets.map(p => p.name));

  log.section('Generating Pallet Pages');

  // Build detailed pallet lookup if available
  const detailedPalletMap = new Map<string, DetailedPalletMetadata>();
  if (detailedMetadata) {
    for (const p of detailedMetadata.pallets) {
      detailedPalletMap.set(p.name.toLowerCase(), p);
    }
  }

  // Generate all pallet pages
  for (const pallet of allPallets) {
    const hooksWithCategory = palletToHooks.get(pallet.name.toLowerCase()) || [];
    const entities = palletToEntities.get(pallet.name.toLowerCase()) || [];
    const sdkRefs = palletToSDK.get(pallet.name.toLowerCase()) || [];
    const detailed = detailedPalletMap.get(pallet.name.toLowerCase());
    const mdxContent = generatePalletMdx(pallet, hooksWithCategory, entities, sdkRefs, storageToSDK, metadata, detailed, handlerIndex, indexerSource, eventToHandlerMap, validEntityNames);
    const filePath = join(palletsOutputPath, `${pallet.name}.mdx`);
    writeFileSync(filePath, mdxContent);
  }

  log.success(`Generated ${allPallets.length} pallet pages`);

  // Index page is auto-generated by Docusaurus sidebar (generated-index)

  // Generate version manifest for tracking and comparison
  const manifestPath = join(outputPath, 'reference/pallets/version-manifest.json');
  const manifest = generateVersionManifest(metadata, allPallets);
  writeFileSync(manifestPath, JSON.stringify(manifest, null, 2));
  log.info(`Generated version manifest: ${manifestPath}`);

  log.section('Generation Complete');
  console.log(`\n  Output: ${palletsOutputPath}/`);
  console.log(`  Pages: ${allPallets.length}\n`);
}

function loadLatestExtraction<T>(baseDir: string, layer: string): T | null {
  const layerDir = join(baseDir, layer);
  if (!existsSync(layerDir)) return null;

  const files = readdirSync(layerDir).filter(f => f.endsWith('.json'));
  if (files.length === 0) return null;

  if (files.includes('extraction.json')) {
    return readJSON<T>(join(layerDir, 'extraction.json'));
  }

  const sortedFiles = files.sort((a, b) => {
    const statA = statSync(join(layerDir, a));
    const statB = statSync(join(layerDir, b));
    return statB.mtime.getTime() - statA.mtime.getTime();
  });

  return readJSON<T>(join(layerDir, sortedFiles[0]));
}

// Note: Pallet-to-hooks and pallet-to-entities mappings are now loaded
// from the cross-reference index (cross-references.json) generated by
// npm run synthesize:crossref. This ensures consistency across all synthesizers.

// Convert PascalCase to snake_case for file paths
function toSnakeCase(str: string): string {
  return str
    .replace(/([A-Z])/g, '_$1')
    .toLowerCase()
    .replace(/^_/, '');
}

// Convert snake_case or kebab-case to PascalCase for matching
function toPascalCase(str: string): string {
  return str
    .split(/[-_]/)
    .map(part => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
    .join('');
}

// Dependency source information from Cargo.lock
interface DependencySource {
  crateName: string;      // crate name (e.g., "pallet-ismp")
  version: string;        // version string (e.g., "16.1.0")
  sourceType: 'git' | 'registry';
  // For git sources:
  gitUrl?: string;        // Full git URL
  repo?: string;          // owner/repo (e.g., "polytope-labs/hyperbridge")
  forkRepo?: string;      // fork repo if different from upstream
  branch?: string;        // branch name
  commit?: string;        // exact commit hash (40 chars)
  // For registry sources:
  registryUrl?: string;
}

// External pallet source from Cargo.lock (includes version info)
interface ExternalPalletSource {
  name: string;           // crate name (e.g., "pallet-ismp")
  palletName: string;     // pallet name (e.g., "Ismp")
  version: string;        // crate version (e.g., "16.1.0")
  gitUrl: string;         // full git URL
  repo: string;           // extracted repo (e.g., "polytope-labs/hyperbridge")
  forkRepo?: string;      // original fork repo if using a fork
  branch?: string;        // branch if specified
  commit?: string;        // exact commit hash
  cratesIoUrl: string;    // crates.io URL (always valid for published crates)
  githubUrl: string;      // GitHub repo URL at branch
}

// Cache for external pallet sources parsed from Cargo.lock
let externalPalletsCache: Map<string, ExternalPalletSource> | null = null;

// Cache for workspace member paths fetched from remote Cargo.toml files
// =============================================================================
// WORKSPACE MEMBERS CACHE
// Fetches Cargo.toml from external repos to get exact crate paths
// Uses [workspace.dependencies] for direct crate-name -> path mapping
// =============================================================================

const workspaceMembersCache: Map<string, Map<string, string>> = new Map();

/**
 * Fetch workspace Cargo.toml and parse crate paths.
 * Prioritizes [workspace.dependencies] which has explicit crate-name = { path = "..." } mappings.
 * Falls back to [workspace] members for crates not in dependencies.
 */
async function fetchWorkspaceMembers(repo: string, branch: string): Promise<Map<string, string>> {
  const cacheKey = `${repo}@${branch}`;
  if (workspaceMembersCache.has(cacheKey)) {
    return workspaceMembersCache.get(cacheKey)!;
  }

  const crateToPath = new Map<string, string>();

  try {
    const url = `https://raw.githubusercontent.com/${repo}/${branch}/Cargo.toml`;
    log.info(`Fetching workspace members from ${repo}...`);

    const response = await fetch(url);
    if (!response.ok) {
      log.warn(`Failed to fetch ${url}: ${response.status}`);
      workspaceMembersCache.set(cacheKey, crateToPath);
      return crateToPath;
    }

    const content = await response.text();

    // Parse [workspace.dependencies] which has explicit crate-name = { path = "..." } mappings
    // This is more reliable than deriving names from directory paths
    const depsMatch = content.match(/\[workspace\.dependencies\]([\s\S]*?)(?:\n\[|\n$)/);
    if (depsMatch) {
      // Match patterns like: crate-name = { path = "path/to/crate", ... }
      const depMatches = depsMatch[1].matchAll(/^([a-zA-Z0-9_-]+)\s*=\s*\{[^}]*path\s*=\s*"([^"]+)"/gm);
      for (const match of depMatches) {
        const crateName = match[1];
        const path = match[2];
        crateToPath.set(crateName, path);
      }
    }

    // Also parse workspace members for crates not in dependencies
    const membersMatch = content.match(/\[workspace\][\s\S]*?members\s*=\s*\[([\s\S]*?)\]/);
    if (membersMatch) {
      const membersContent = membersMatch[1];
      const pathMatches = membersContent.matchAll(/"([^"]+)"/g);

      for (const match of pathMatches) {
        const path = match[1];
        if (path.includes('*')) continue; // Skip glob patterns

        // Derive crate name from last path segment
        const segments = path.split('/');
        const lastName = segments[segments.length - 1];

        // Only add if not already in the map (dependencies take priority)
        if (!crateToPath.has(lastName)) {
          crateToPath.set(lastName, path);
        }
      }
    }

    log.info(`Found ${crateToPath.size} crate paths in ${repo}`);
  } catch (err) {
    log.warn(`Error fetching workspace for ${repo}: ${err}`);
  }

  workspaceMembersCache.set(cacheKey, crateToPath);
  return crateToPath;
}

// Synchronous version using pre-fetched cache
function getWorkspacePath(repo: string, ref: string, crateName: string): string | undefined {
  const cacheKey = `${repo}@${ref}`;
  const members = workspaceMembersCache.get(cacheKey);
  if (!members) return undefined;

  // Direct lookup by crate name (from [workspace.dependencies])
  if (members.has(crateName)) {
    return members.get(crateName);
  }

  // Fallback: try directory name derived from crate name
  const shortName = crateName
    .replace(/^cumulus-pallet-/, '')
    .replace(/^pallet-/, '')
    .replace(/^orml-/, '');

  if (members.has(shortName)) {
    return members.get(shortName);
  }

  return undefined;
}

// Known repository labels and upstream mappings
interface RepoConfig {
  upstream: string;        // Canonical upstream repo (for forks)
  label: string;           // Display label
}

const KNOWN_REPOS: Record<string, RepoConfig> = {
  // Polkadot SDK (and forks)
  'paritytech/polkadot-sdk': { upstream: 'paritytech/polkadot-sdk', label: 'Polkadot SDK' },
  'galacticcouncil/polkadot-sdk': { upstream: 'paritytech/polkadot-sdk', label: 'Polkadot SDK' },
  // ORML (and forks)
  'open-web3-stack/open-runtime-module-library': { upstream: 'open-web3-stack/open-runtime-module-library', label: 'ORML' },
  'galacticcouncil/open-runtime-module-library': { upstream: 'open-web3-stack/open-runtime-module-library', label: 'ORML' },
  // Hyperbridge / ISMP
  'polytope-labs/hyperbridge': { upstream: 'polytope-labs/hyperbridge', label: 'Hyperbridge' },
  // Frontier (EVM)
  'moonbeam-foundation/frontier': { upstream: 'polkadot-evm/frontier', label: 'Frontier' },
  'moonbeam-foundation/evm': { upstream: 'rust-ethereum/evm', label: 'EVM' },
};

// Get all possible crate names for a pallet name
// Uses construct_runtime! parsing first, then falls back to common patterns
function getCrateNamesForPallet(palletName: string): string[] {
  const name = palletName.toLowerCase().replace(/_/g, '');
  const snakeName = toSnakeCase(palletName).replace(/_/g, '-');

  const candidates: string[] = [];

  // First, check the parsed construct_runtime! mapping
  const palletToCrate = parsePalletToCrateMapping();
  const exactCrate = palletToCrate.get(name);
  if (exactCrate) {
    candidates.push(exactCrate.crateName);
  }

  // Add common patterns as fallback
  candidates.push(`pallet-${snakeName}`);      // pallet-balances
  candidates.push(`orml-${snakeName}`);        // orml-tokens
  candidates.push(snakeName);                   // ismp-parachain
  candidates.push(`${snakeName}-pallet`);      // some-pallet

  return [...new Set(candidates)]; // Remove duplicates
}

// Look up dependency info from Cargo.lock by pallet name
function getDependencyForPallet(palletName: string): DependencySource | undefined {
  const allDeps = parseAllCargoLockDependencies();
  const candidates = getCrateNamesForPallet(palletName);

  for (const crateName of candidates) {
    const dep = allDeps.get(crateName);
    if (dep) return dep;
  }

  return undefined;
}

// Cache for all dependency sources (not just pallets)
let allDependenciesCache: Map<string, DependencySource> | null = null;

// Parse ALL Cargo.lock dependencies for complete version tracking
function parseAllCargoLockDependencies(): Map<string, DependencySource> {
  if (allDependenciesCache) return allDependenciesCache;

  allDependenciesCache = new Map();
  const cargoLockPath = join(HYDRADX_NODE_PATH, 'Cargo.lock');

  if (!existsSync(cargoLockPath)) {
    log.warn('Cargo.lock not found, dependency tracking disabled');
    return allDependenciesCache;
  }

  try {
    const content = readFileSync(cargoLockPath, 'utf-8');
    const packages = content.split('[[package]]');

    for (const pkg of packages) {
      const nameMatch = pkg.match(/^name\s*=\s*"([^"]+)"/m);
      const versionMatch = pkg.match(/^version\s*=\s*"([^"]+)"/m);
      const sourceMatch = pkg.match(/^source\s*=\s*"([^"]+)"/m);

      if (!nameMatch || !versionMatch) continue;

      const crateName = nameMatch[1];
      const version = versionMatch[1];
      const sourceUrl = sourceMatch ? sourceMatch[1] : '';

      const dep: DependencySource = {
        crateName,
        version,
        sourceType: sourceUrl.startsWith('git+') ? 'git' : 'registry',
      };

      if (dep.sourceType === 'git') {
        // Parse: git+https://github.com/owner/repo?branch=xxx#commit
        const gitUrl = sourceUrl.replace('git+', '');
        dep.gitUrl = gitUrl;

        // Extract repo, branch, and commit
        const urlMatch = gitUrl.match(/https:\/\/github\.com\/([^/?#]+\/[^/?#]+)(?:\?branch=([^#]+))?(?:#([a-f0-9]+))?/);
        if (urlMatch) {
          dep.forkRepo = urlMatch[1];  // Original fork repo
          dep.branch = urlMatch[2] || 'main';
          dep.commit = urlMatch[3];    // Exact commit hash

          // Map to upstream repo for canonical display
          const repoConfig = KNOWN_REPOS[urlMatch[1]];
          dep.repo = repoConfig?.upstream || urlMatch[1];
        }
      } else {
        dep.registryUrl = sourceUrl;
      }

      allDependenciesCache.set(crateName, dep);
    }

    log.info(`Parsed ${allDependenciesCache.size} dependencies from Cargo.lock`);
  } catch (err) {
    log.warn(`Failed to parse Cargo.lock: ${err}`);
  }

  return allDependenciesCache;
}

// Parse Cargo.lock to find external pallet sources
function parseCargoLock(): Map<string, ExternalPalletSource> {
  if (externalPalletsCache) return externalPalletsCache;

  externalPalletsCache = new Map();
  const allDeps = parseAllCargoLockDependencies();

  for (const [crateName, dep] of allDeps) {
    // Process pallet-*, orml-*, and ismp-related crates from git sources
    if (dep.sourceType !== 'git') continue;
    if (!crateName.startsWith('pallet-') &&
        !crateName.startsWith('orml-') &&
        !crateName.includes('ismp')) continue;

    if (!dep.repo) continue;

    // Convert crate name to pallet name
    // pallet-ismp -> Ismp, ismp-parachain -> IsmpParachain
    // orml-tokens -> Tokens, orml-vesting -> Vesting
    let palletName = crateName
      .replace(/^pallet-/, '')
      .replace(/^orml-/, '')
      .replace(/-pallet$/, '');
    palletName = toPascalCase(palletName);

    // Build bulletproof URLs
    const cratesIoUrl = `https://crates.io/crates/${crateName}`;
    const githubUrl = `https://github.com/${dep.repo}`;

    const source: ExternalPalletSource = {
      name: crateName,
      palletName,
      version: dep.version,
      gitUrl: dep.gitUrl || '',
      repo: dep.repo,
      forkRepo: dep.forkRepo !== dep.repo ? dep.forkRepo : undefined,
      branch: dep.branch,
      commit: dep.commit,
      cratesIoUrl,
      githubUrl,
    };

    // Store by lowercase pallet name for lookup
    externalPalletsCache.set(palletName.toLowerCase(), source);
  }

  if (externalPalletsCache.size > 0) {
    log.info(`Found ${externalPalletsCache.size} external pallet sources`);
  }

  return externalPalletsCache;
}

// Get the default branch for a known repo
function getDefaultBranch(repo: string): string {
  // Most repos use 'main', some use 'master'
  const masterBranches = [
    'paritytech/polkadot-sdk',
    'open-web3-stack/open-runtime-module-library',
    'galacticcouncil/HydraDX-node',
  ];
  return masterBranches.includes(repo) ? 'master' : 'main';
}

// Pre-fetch workspace members for all unique repos to get exact paths
// Uses the ACTUAL branch/commit from Cargo.lock, not default branches
async function prefetchWorkspaceMembers(): Promise<void> {
  const externalPallets = parseCargoLock();

  // Collect unique repo@ref combinations from actual Cargo.lock sources
  // Use commit hash when available for exact reproducibility
  const repoRefs = new Set<string>();
  for (const source of externalPallets.values()) {
    // Prefer commit hash, fallback to branch from Cargo.lock
    const ref = source.commit || source.branch || 'main';
    const repo = source.forkRepo || source.repo;
    repoRefs.add(`${repo}@${ref}`);
  }

  // Fetch workspace members for each repo@ref in parallel
  const fetchPromises = Array.from(repoRefs).map(key => {
    const [repo, ref] = key.split('@');
    return fetchWorkspaceMembers(repo, ref);
  });

  await Promise.all(fetchPromises);
}

// Pallet source information
interface PalletSource {
  repo: 'hydradx' | 'polkadot-sdk' | 'orml' | 'cumulus' | 'external';
  path: string;
  cratesIoUrl?: string;   // crates.io URL for external pallets
  githubUrl?: string;     // GitHub repo URL for external pallets
  crateName?: string;     // Original crate name
  version?: string;       // Crate version
  commit?: string;        // Exact commit hash
  branch?: string;        // Branch name
  forkRepo?: string;      // Fork repo if using a fork
  instance?: string;      // Instance name (e.g., "Instance2") for multi-instance pallets
}

// Determine the source repository for a pallet
// Uses construct_runtime! parsing and Cargo.lock for accurate detection
// Paths are resolved from workspace Cargo.toml files (no hardcoded mappings)
function getPalletSource(palletName: string): PalletSource {
  const name = palletName.toLowerCase().replace(/_/g, '');
  const snakeName = toSnakeCase(palletName);

  // Get runtime info from construct_runtime! (includes instance info)
  const palletToCrate = parsePalletToCrateMapping();
  const runtimeInfo = palletToCrate.get(name);
  const crateName = runtimeInfo?.crateName;
  const instance = runtimeInfo?.instance;

  // Look up the crate in Cargo.lock
  const allDeps = parseAllCargoLockDependencies();
  const dep = crateName ? allDeps.get(crateName) : undefined;

  // If crate found in Cargo.lock with git source
  if (dep && dep.sourceType === 'git' && dep.repo) {
    // Determine repo type and path based on upstream repo
    const upstreamRepo = dep.repo;
    const forkRepo = dep.forkRepo || upstreamRepo;
    const branch = dep.branch || 'main';
    // Use commit for workspace lookup (matches prefetchWorkspaceMembers cache key)
    const workspaceRef = dep.commit || branch;

    // Polkadot SDK pallets - get path from workspace Cargo.toml
    if (upstreamRepo === 'paritytech/polkadot-sdk') {
      // Try to get path from pre-fetched workspace members
      const workspacePath = getWorkspacePath(forkRepo, workspaceRef, dep.crateName);
      // Fallback: derive path from crate name
      let fallbackPath: string;
      if (dep.crateName.startsWith('cumulus-pallet-')) {
        // cumulus-pallet-parachain-system -> cumulus/pallets/parachain-system
        fallbackPath = `cumulus/pallets/${dep.crateName.replace('cumulus-pallet-', '')}`;
      } else if (dep.crateName.startsWith('frame-')) {
        fallbackPath = `substrate/frame/${dep.crateName.replace('frame-', '')}`;
      } else {
        fallbackPath = `substrate/frame/${dep.crateName.replace('pallet-', '')}`;
      }
      const path = workspacePath || fallbackPath;

      return {
        repo: 'polkadot-sdk',
        path,
        crateName: dep.crateName,
        version: dep.version,
        commit: dep.commit,
        branch: dep.branch,
        forkRepo,  // Use the fallback variable
        instance,
      };
    }

    // ORML pallets - get path from workspace Cargo.toml
    if (upstreamRepo === 'open-web3-stack/open-runtime-module-library') {
      // Try to get path from pre-fetched workspace members
      const workspacePath = getWorkspacePath(forkRepo, workspaceRef, dep.crateName);
      // Fallback: orml-tokens -> tokens
      const fallbackPath = dep.crateName.replace('orml-', '');
      const path = workspacePath || fallbackPath;

      return {
        repo: 'orml',
        path,
        crateName: dep.crateName,
        version: dep.version,
        commit: dep.commit,
        branch: dep.branch,
        forkRepo,  // Use the fallback variable
        instance,
      };
    }

    // Other external pallets (Hyperbridge, Frontier, etc.)
    // Try to get path from workspace Cargo.toml
    const workspacePath = getWorkspacePath(forkRepo, workspaceRef, dep.crateName);

    return {
      repo: 'external',
      path: workspacePath || '',
      cratesIoUrl: `https://crates.io/crates/${dep.crateName}`,
      githubUrl: `https://github.com/${upstreamRepo}`,
      crateName: dep.crateName,
      version: dep.version,
      commit: dep.commit,
      branch: dep.branch,
      forkRepo,  // Use the fallback variable
      instance,
    };
  }

  // If crate found but no source or is local -> it's a HydraDX pallet
  // Also check if the pallet directory exists locally
  if (crateName) {
    // Try common paths for HydraDX pallets
    const baseName = crateName.replace(/^pallet-/, '').replace(/^warehouse-/, '');
    const possiblePaths = [
      `pallets/${crateName.replace(/^pallet-/, '').replace(/-/g, '_')}`,
      `pallets/${crateName.replace(/^pallet-/, '')}`,
      `pallets/${baseName}`,  // warehouse-liquidity-mining -> liquidity-mining
      `pallets/${baseName.replace(/-/g, '_')}`,
      `pallets/${snakeName}`,
      `runtime/hydradx/src/governance`,  // For pallet_custom_origins
    ];

    for (const path of possiblePaths) {
      if (existsSync(join(HYDRADX_NODE_PATH, path))) {
        return { repo: 'hydradx', path, crateName, instance };
      }
    }
  }

  // Check external pallets cache (for legacy compatibility)
  const externalPallets = parseCargoLock();
  const external = externalPallets.get(name);
  if (external) {
    return {
      repo: 'external',
      path: '',
      cratesIoUrl: external.cratesIoUrl,
      githubUrl: external.githubUrl,
      crateName: external.name,
      version: external.version,
      commit: external.commit,
      branch: external.branch,
      forkRepo: external.forkRepo,
      instance,
    };
  }

  // Default to HydraDX for unknown pallets
  return { repo: 'hydradx', path: `pallets/${snakeName}`, instance };
}

// Pallet links structure
interface PalletLinks {
  cratesIo?: string;    // crates.io page (versions, docs link, repo link)
  docsRs?: string;      // docs.rs source viewer (direct to source code)
  github: string;       // GitHub repo or path (at exact commit if available)
  // Version tracking info
  version?: string;     // Crate version
  commit?: string;      // Exact commit hash
  branch?: string;      // Branch name
  forkRepo?: string;    // Fork repo if using a fork
  instance?: string;    // Instance name (e.g., "Instance2") for multi-instance pallets
  crateName?: string;   // Crate name (for display when different from pallet name)
}

// Build links for a pallet - includes crates.io, docs.rs source, and GitHub
// Uses exact commit hashes from Cargo.lock for reproducible links
function buildPalletLinks(palletName: string): PalletLinks {
  const source = getPalletSource(palletName);

  switch (source.repo) {
    case 'external': {
      // External crates: use crates.io + docs.rs source viewer + GitHub with path
      const externalPallets = parseCargoLock();
      const name = palletName.toLowerCase().replace(/_/g, '');
      const external = externalPallets.get(name);

      let githubUrl = source.githubUrl || 'https://github.com/galacticcouncil/HydraDX-node';

      // Try to get exact path from workspace Cargo.toml or use known patterns
      if (external && source.crateName) {
        // Use the ACTUAL repo and ref from Cargo.lock (commit or branch)
        const actualRepo = external.forkRepo || external.repo;
        const actualRef = external.commit || external.branch || 'main';

        // Get path from workspace using the exact ref we're linking to
        let path = getWorkspacePath(actualRepo, actualRef, source.crateName);

        // If not found in workspace, use known repo patterns
        if (!path) {
          if (external.repo === 'open-web3-stack/open-runtime-module-library') {
            // ORML: orml-tokens -> tokens/
            path = source.crateName.replace(/^orml-/, '');
          } else if (external.repo === 'paritytech/polkadot-sdk' && source.crateName.startsWith('pallet-')) {
            // Polkadot SDK fallback: pallet-foo -> substrate/frame/foo
            path = `substrate/frame/${source.crateName.replace(/^pallet-/, '')}`;
          } else if (external.repo === 'polytope-labs/hyperbridge') {
            // Hyperbridge fallback patterns
            if (source.crateName.startsWith('pallet-')) {
              // pallet-ismp -> modules/pallets/ismp
              path = `modules/pallets/${source.crateName.replace(/^pallet-/, '')}`;
            } else if (source.crateName === 'ismp-parachain') {
              // Special case: ismp-parachain is at modules/ismp/clients/parachain/client
              path = 'modules/ismp/clients/parachain/client';
            } else if (source.crateName.startsWith('ismp-')) {
              // Other ismp-* crates
              const suffix = source.crateName.replace(/^ismp-/, '');
              path = `modules/ismp/clients/${suffix}`;
            }
          }
        }

        // Build URL using actual repo and ref from Cargo.lock
        if (path) {
          githubUrl = `https://github.com/${actualRepo}/tree/${actualRef}/${path}`;
        } else {
          githubUrl = `https://github.com/${actualRepo}/tree/${actualRef}`;
        }
      }

      return {
        cratesIo: source.cratesIoUrl,
        docsRs: source.crateName ? `https://docs.rs/crate/${source.crateName}/${source.version || 'latest'}/source/` : undefined,
        github: githubUrl,
        version: source.version,
        commit: source.commit,
        branch: source.branch,
        forkRepo: source.forkRepo,
        instance: source.instance,
        crateName: source.crateName,
      };
    }
    case 'hydradx': {
      // HydraDX pallets: direct GitHub path with actual commit
      const hydradxInfo = getHydradxGitInfo();
      return {
        github: `https://github.com/galacticcouncil/HydraDX-node/tree/${hydradxInfo.commit}/${source.path}`,
        commit: hydradxInfo.commit,
        branch: hydradxInfo.branch,
        instance: source.instance,
        crateName: source.crateName,
      };
    }
    case 'polkadot-sdk': {
      // Use version info from source (already populated from Cargo.lock)
      const crateName = source.crateName || `pallet-${toSnakeCase(palletName).replace(/_/g, '-')}`;
      const ref = source.commit || 'master';
      const repo = source.forkRepo || 'paritytech/polkadot-sdk';
      return {
        cratesIo: `https://crates.io/crates/${crateName}`,
        docsRs: `https://docs.rs/crate/${crateName}/${source.version || 'latest'}/source/`,
        github: `https://github.com/${repo}/tree/${ref}/${source.path}`,
        version: source.version,
        commit: source.commit,
        branch: source.branch,
        forkRepo: source.forkRepo,
        instance: source.instance,
        crateName: crateName,
      };
    }
    case 'orml': {
      // Use version info from source (already populated from Cargo.lock)
      const crateName = source.crateName || `orml-${toSnakeCase(palletName).replace(/_/g, '-')}`;
      const ref = source.commit || 'master';
      const repo = source.forkRepo || 'open-web3-stack/open-runtime-module-library';
      return {
        cratesIo: `https://crates.io/crates/${crateName}`,
        docsRs: `https://docs.rs/crate/${crateName}/${source.version || 'latest'}/source/`,
        github: `https://github.com/${repo}/tree/${ref}/${source.path}`,
        version: source.version,
        commit: source.commit,
        branch: source.branch,
        forkRepo: source.forkRepo,
        instance: source.instance,
        crateName: crateName,
      };
    }
    case 'cumulus': {
      // Use version info from source (already populated from Cargo.lock)
      const crateName = source.crateName || `cumulus-${toSnakeCase(palletName).replace(/_/g, '-')}`;
      const ref = source.commit || 'master';
      const repo = source.forkRepo || 'paritytech/polkadot-sdk';
      return {
        github: `https://github.com/${repo}/tree/${ref}/cumulus/${source.path}`,
        version: source.version,
        commit: source.commit,
        branch: source.branch,
        forkRepo: source.forkRepo,
        instance: source.instance,
        crateName: crateName,
      };
    }
    default: {
      // Unknown pallets default to HydraDX with actual commit
      const hydradxInfo = getHydradxGitInfo();
      return {
        github: `https://github.com/galacticcouncil/HydraDX-node/tree/${hydradxInfo.commit}/${source.path}`,
        commit: hydradxInfo.commit,
        branch: hydradxInfo.branch,
        instance: source.instance,
        crateName: source.crateName,
      };
    }
  }
}

// Legacy function for backward compatibility
function buildGitHubLink(palletName: string): string {
  return buildPalletLinks(palletName).github;
}

// Get source label for display
function getSourceLabel(palletName: string): string {
  const source = getPalletSource(palletName);

  // For external pallets, get label from KNOWN_REPOS or derive from repo name
  if (source.repo === 'external') {
    const externalPallets = parseCargoLock();
    const name = palletName.toLowerCase().replace(/_/g, '');
    const external = externalPallets.get(name);
    if (external) {
      // Check if we have a known repo config with a label
      const repoConfig = KNOWN_REPOS[external.repo];
      if (repoConfig) {
        return repoConfig.label;
      }
      // Fallback: extract repo name: "polytope-labs/hyperbridge" -> "Hyperbridge"
      const repoName = external.repo.split('/')[1];
      return toPascalCase(repoName);
    }
    return 'External';
  }

  switch (source.repo) {
    case 'hydradx': return 'HydraDX';
    case 'polkadot-sdk': return 'Polkadot SDK';
    case 'orml': return 'ORML';
    case 'cumulus': return 'Polkadot SDK (Cumulus)';
    default: return 'HydraDX';
  }
}

// Build Subscan runtime link
function buildSubscanLink(palletName: string): string {
  return `https://hydradx.subscan.io/runtime/${palletName}`;
}

// =============================================================================
// PALLET DOCUMENTATION FETCHING
// Reads README.md and lib.rs doc comments for each pallet
// - HydraDX pallets: Read from local filesystem
// - External pallets: Fetched from GitHub (raw.githubusercontent.com)
// =============================================================================

interface PalletDocs {
  readme: string | null;  // Full README.md content (cleaned)
  libRs: string | null;   // lib.rs //! doc comments (extracted)
}

// Cache for pre-fetched external pallet docs
const externalDocsCache = new Map<string, PalletDocs>();

/**
 * Fetch documentation from an external GitHub repository.
 * Attempts to fetch both README.md and lib.rs doc comments.
 */
async function fetchExternalPalletDocs(
  repo: string,
  commit: string,
  path: string
): Promise<PalletDocs> {
  const result: PalletDocs = { readme: null, libRs: null };
  if (!path) return result;

  const baseUrl = `https://raw.githubusercontent.com/${repo}/${commit}/${path}`;

  // Try to fetch lib.rs
  try {
    const libRsUrl = `${baseUrl}/src/lib.rs`;
    const response = await fetch(libRsUrl);
    if (response.ok) {
      const content = await response.text();
      result.libRs = extractLibRsDocComments(content);
    }
  } catch {
    // Ignore fetch errors
  }

  // Try to fetch README.md
  try {
    const readmeUrl = `${baseUrl}/README.md`;
    const response = await fetch(readmeUrl);
    if (response.ok) {
      const content = await response.text();
      result.readme = cleanReadmeContent(content);
    }
  } catch {
    // Ignore fetch errors
  }

  return result;
}

/**
 * Pre-fetch documentation for all external pallets in parallel.
 * Called once during initialization to populate externalDocsCache.
 */
async function prefetchExternalPalletDocs(palletNames: string[]): Promise<void> {
  const fetchPromises: Promise<void>[] = [];

  for (const palletName of palletNames) {
    const source = getPalletSource(palletName);

    // Skip HydraDX pallets (we read those locally)
    if (source.repo === 'hydradx') continue;

    // Skip if no path or repo info
    if (!source.path || !source.forkRepo || !source.commit) continue;

    const cacheKey = `${source.forkRepo}/${source.commit}/${source.path}`;
    if (externalDocsCache.has(cacheKey)) continue;

    fetchPromises.push(
      fetchExternalPalletDocs(source.forkRepo, source.commit, source.path)
        .then(docs => {
          externalDocsCache.set(cacheKey, docs);
        })
    );
  }

  if (fetchPromises.length > 0) {
    log.info(`Fetching docs for ${fetchPromises.length} external pallets...`);
    await Promise.all(fetchPromises);
    const withDocs = Array.from(externalDocsCache.values()).filter(d => d.readme || d.libRs).length;
    log.info(`Fetched docs for ${withDocs} external pallets`);
  }
}

/**
 * Get documentation for a pallet.
 * - HydraDX pallets: Read from local repos/hydration-node/
 * - External pallets: Use pre-fetched cache from GitHub
 */
function readPalletDocs(palletName: string): PalletDocs {
  const source = getPalletSource(palletName);
  const result: PalletDocs = { readme: null, libRs: null };

  // For HydraDX pallets, read from local filesystem
  if (source.repo === 'hydradx') {
    // Try README.md
    const readmePath = join(HYDRADX_NODE_PATH, source.path, 'README.md');
    if (existsSync(readmePath)) {
      try {
        const content = readFileSync(readmePath, 'utf-8');
        result.readme = cleanReadmeContent(content);
      } catch {
        // Ignore errors
      }
    }

    // Try lib.rs doc comments
    const libRsPath = join(HYDRADX_NODE_PATH, source.path, 'src/lib.rs');
    if (existsSync(libRsPath)) {
      try {
        const content = readFileSync(libRsPath, 'utf-8');
        result.libRs = extractLibRsDocComments(content);
      } catch {
        // Ignore errors
      }
    }

    return result;
  }

  // For external pallets, use pre-fetched cache
  if (source.forkRepo && source.commit && source.path) {
    const cacheKey = `${source.forkRepo}/${source.commit}/${source.path}`;
    const cached = externalDocsCache.get(cacheKey);
    if (cached) {
      return cached;
    }
  }

  return result;
}

/**
 * Clean up README.md content for display.
 * - Removes title lines (# pallet-name)
 * - Removes license section at the end
 * - Collapses multiple blank lines
 */
function cleanReadmeContent(content: string): string | null {
  const lines = content.split('\n');
  const result: string[] = [];
  let skipLicense = true;

  for (const line of lines) {
    // Skip title line (# pallet-name or # Pallet Name)
    if (line.startsWith('# ') && result.length === 0) {
      continue;
    }
    // Skip ## Pallet header
    if (line.startsWith('## ') && line.toLowerCase().includes('pallet') && result.length === 0) {
      continue;
    }
    // Skip license section at the end
    if (line.toLowerCase().startsWith('license')) {
      break;
    }
    // Start capturing after we see real content
    if (line.trim()) {
      skipLicense = false;
    }
    if (!skipLicense) {
      result.push(line);
    }
  }

  if (result.length === 0) return null;

  // Clean up: collapse multiple blank lines
  let cleaned = result.join('\n');
  cleaned = cleaned.replace(/\n{3,}/g, '\n\n');
  return cleaned.trim() || null;
}

/**
 * Extract Rust doc comments (//!) from lib.rs.
 * These appear at the top of the file and provide module-level documentation.
 * Converts ## headers to ### to fit within pallet doc hierarchy.
 */
function extractLibRsDocComments(content: string): string | null {
  const lines = content.split('\n');
  const docLines: string[] = [];
  let inDocSection = false;
  let foundDoc = false;

  for (const line of lines) {
    const trimmed = line.trim();

    // Skip license comments (// without !)
    if (trimmed.startsWith('// ') && !trimmed.startsWith('//!')) {
      if (!foundDoc) continue; // Skip initial license block
      else break; // Stop at regular comments after doc comments
    }

    // Doc comments start with //!
    if (trimmed.startsWith('//!')) {
      foundDoc = true;
      inDocSection = true;

      // Empty doc line (just "//!")
      if (trimmed === '//!') {
        docLines.push('');
        continue;
      }

      // Remove the //! prefix
      let docContent = trimmed.slice(3);
      // Preserve leading space for indentation, but trim trailing
      if (docContent.startsWith(' ')) docContent = docContent.slice(1);

      // Skip the main title (e.g., "# Omnipool pallet")
      if (docContent.startsWith('# ') && docLines.length === 0) {
        continue;
      }

      // Convert ## headers to ### (since we're inside pallet doc)
      if (docContent.startsWith('## ')) {
        docContent = '#' + docContent;
      }

      docLines.push(docContent);
      continue;
    }

    // Non-doc line after doc section - we're done
    if (inDocSection && !trimmed.startsWith('//!')) {
      break;
    }

    // Skip #![...] attributes
    if (trimmed.startsWith('#![')) {
      if (foundDoc) break;
      continue;
    }
  }

  if (docLines.length === 0) return null;

  // Clean up: remove excessive blank lines
  const cleanedLines: string[] = [];
  let prevWasBlank = false;

  for (const line of docLines) {
    if (line === '') {
      if (!prevWasBlank && cleanedLines.length > 0) {
        cleanedLines.push('');
        prevWasBlank = true;
      }
    } else {
      cleanedLines.push(line);
      prevWasBlank = false;
    }
  }

  return cleanedLines.join('\n').trim() || null;
}

// Clean up docs string for display (escape MDX-sensitive characters)
function cleanDocs(docs: string): string {
  if (!docs) return '';

  let result = docs;

  // Remove rustdoc relative links like [text](./trait.Config.html) or [text](../pallet_foo/index.html)
  // These don't work in the docs site context
  result = result.replace(
    /\[([^\]]+)\]\((?:\.\/|\.\.\/)[^)]*\.html[^)]*\)/g,
    '`$1`'  // Convert to inline code instead
  );

  // Remove rustdoc links to .html files (trait.Config.html, enum.Call.html, etc.)
  result = result.replace(
    /\[([^\]]+)\]\((?!https?:\/\/)[^)]*\.html[^)]*\)/g,
    '`$1`'
  );

  // Remove standalone rustdoc paths like `design-goals` that would be resolved as relative links
  result = result.replace(
    /\[([^\]]+)\]\((?!https?:\/\/|\/|#)([a-z][a-z0-9_-]*)\)/gi,
    '`$1`'
  );

  // Remove backtick links that look like rustdoc paths: [`Config::HistoryDepth`]
  result = result.replace(
    /\[`([^`]+)`\](?:\([^)]*\))?/g,
    '`$1`'
  );

  // Remove reference-style markdown links: [`Config`]: ./trait.Config.html
  result = result.replace(
    /^\[`?[^\]]+`?\]:\s*(?:\.\/|\.\.\/)?[^\s]+\.html.*$/gm,
    ''
  );

  // Remove reference-style links to non-URL targets: [Config]: design-goals
  result = result.replace(
    /^\[`?[^\]]+`?\]:\s*(?!https?:\/\/)[^\s]+$/gm,
    ''
  );

  // First, convert URLs in angle brackets to markdown links: <https://...> -> [link](url)
  result = result.replace(/<(https?:\/\/[^>]+)>/g, (_match, url) => {
    // Create a short display text from the URL
    const displayUrl = url.length > 60 ? url.substring(0, 57) + '...' : url;
    return `[${displayUrl}](${url})`;
  });

  // Handle code blocks: ```lang ... ``` -> proper markdown code blocks
  // These can appear inline in the docs, need to format them properly
  result = result.replace(/```(\w*)\s+([\s\S]*?)```/g, (_match, lang, code) => {
    const cleanCode = code.trim();
    return `\n\n\`\`\`${lang}\n${cleanCode}\n\`\`\`\n\n`;
  });

  // Handle `backtick code` - escape MDX chars inside backticks carefully
  // First, temporarily protect backtick content
  const backtickProtected: string[] = [];
  result = result.replace(/`([^`]+)`/g, (_match, code) => {
    backtickProtected.push(code);
    return `__BACKTICK_${backtickProtected.length - 1}__`;
  });

  // Now escape MDX-sensitive characters in remaining text
  result = result
    .replace(/</g, '\\<')
    .replace(/>/g, '\\>')
    .replace(/\{/g, '\\{')
    .replace(/\}/g, '\\}');

  // Restore backtick content (don't escape inside backticks)
  result = result.replace(/__BACKTICK_(\d+)__/g, (_match, idx) => {
    return '`' + backtickProtected[parseInt(idx)] + '`';
  });

  // Clean up whitespace - normalize but preserve intentional line breaks
  result = result
    .replace(/\n{3,}/g, '\n\n')  // Max 2 newlines
    .replace(/[ \t]+/g, ' ')     // Normalize horizontal whitespace
    .trim();

  return result;
}

// Format type as Rust-like syntax with multi-line for complex types
function formatRustType(type: string): string {
  // Clean up the type string
  const cleaned = type
    .replace(/"/g, '')  // Remove JSON quotes
    .replace(/\s+/g, ' ')  // Normalize whitespace
    .trim();

  // Check if this contains a struct with many fields: {...}
  const braceStart = cleaned.indexOf('{');
  const braceEnd = cleaned.lastIndexOf('}');

  if (braceStart !== -1 && braceEnd > braceStart) {
    const prefix = cleaned.substring(0, braceStart);
    const structContent = cleaned.substring(braceStart + 1, braceEnd);
    const suffix = cleaned.substring(braceEnd + 1);

    // Parse fields
    const fieldPairs = parseStructFields(structContent);

    // If more than 2 fields, format on multiple lines
    if (fieldPairs.length > 2) {
      const formattedFields = fieldPairs
        .map(f => `    ${f.name}: ${f.type},`)
        .join('\n');
      return `${prefix}{\n${formattedFields}\n}${suffix}`;
    }
  }

  // For simpler types, just clean up spacing
  return cleaned
    .replace(/,/g, ', ')
    .replace(/:(?!\s)/g, ': ');
}

// Parse struct fields from a string like "name:Type,other:Type2"
function parseStructFields(fieldsStr: string): { name: string; type: string }[] {
  const fields: { name: string; type: string }[] = [];
  let depth = 0;
  let current = '';

  for (const char of fieldsStr) {
    if (char === '{' || char === '<' || char === '(') depth++;
    else if (char === '}' || char === '>' || char === ')') depth--;

    if (char === ',' && depth === 0) {
      const parsed = parseField(current.trim());
      if (parsed) fields.push(parsed);
      current = '';
    } else {
      current += char;
    }
  }

  // Don't forget the last field
  if (current.trim()) {
    const parsed = parseField(current.trim());
    if (parsed) fields.push(parsed);
  }

  return fields;
}

// Parse a single field like "name:Type" or "name: Type"
function parseField(field: string): { name: string; type: string } | null {
  const colonIdx = field.indexOf(':');
  if (colonIdx === -1) return null;
  return {
    name: field.substring(0, colonIdx).trim(),
    type: field.substring(colonIdx + 1).trim(),
  };
}

function generatePalletMdx(
  pallet: PalletMetadata,
  hooks: { name: string; category: string }[],
  entities: string[],
  sdkRefs: { package: string; method: string }[],
  storageToSDK: Map<string, Array<{ method: string; package: string }>>,
  metadata: ChainMetadata,
  detailed?: DetailedPalletMetadata,
  handlerIndex?: Map<string, { event: string; file: string; line: number }>,
  indexerSource?: { repo: string; commit: string } | null,
  eventToHandlerMap?: Record<string, { handlers: string[]; entities: string[] }>,
  validEntityNames?: Set<string>
): string {
  const palletLinks = buildPalletLinks(pallet.name);
  const subscanLink = buildSubscanLink(pallet.name);
  const sourceLabel = getSourceLabel(pallet.name);
  const palletDocs = readPalletDocs(pallet.name);

  const lines: string[] = [
    '---',
    `title: ${pallet.name}`,
    `description: Runtime pallet documentation`,
    `sidebar_label: ${pallet.name}`,
    '---',
    '',
    `# ${pallet.name}`,
    '',
  ];

  // Add README content if available
  if (palletDocs.readme) {
    lines.push(cleanDocs(palletDocs.readme));
    lines.push('');
  }

  // Add lib.rs doc comments in a collapsible section if available
  if (palletDocs.libRs) {
    lines.push('<details>');
    lines.push('<summary>Code Documentation</summary>');
    lines.push('');
    lines.push(cleanDocs(palletDocs.libRs));
    lines.push('');
    lines.push('</details>');
    lines.push('');
  }

  // Add AI placeholder for additional/missing descriptions
  lines.push('<!-- AI_DESCRIPTION_START -->');
  if (!palletDocs.readme && !palletDocs.libRs) {
    lines.push(`> **TODO**: AI-generated description of what this pallet does.`);
  }
  lines.push('<!-- AI_DESCRIPTION_END -->');
  lines.push('');

  // Calculate counts for section headers
  const storageCount = detailed ? detailed.storage.length : pallet.storage.length;
  const callsCount = detailed
    ? detailed.calls.filter(c => !c.name.startsWith('__Unused')).length
    : pallet.calls.length;
  const eventsCount = detailed ? detailed.events.length : pallet.events.length;
  const constantsCount = detailed ? detailed.constants.length : pallet.constants.length;

  // Quick Reference - two lines for readability
  // Build crate/commit/branch string
  const cratePart = palletLinks.crateName || pallet.name.toLowerCase();
  const commitPart = palletLinks.commit ? palletLinks.commit.substring(0, 8) : '';
  const branchPart = palletLinks.branch || '';
  const instancePart = palletLinks.instance ? ` (${palletLinks.instance})` : '';

  let crateInfo: string;
  if (commitPart && branchPart) {
    crateInfo = `\`${cratePart}/${commitPart}/${branchPart}\`${instancePart}`;
  } else if (commitPart) {
    crateInfo = `\`${cratePart}/${commitPart}\`${instancePart}`;
  } else {
    crateInfo = `\`${cratePart}\`${instancePart}`;
  }

  lines.push(`**Pallet #${pallet.index}** · ${sourceLabel}<br/>`);
  lines.push(crateInfo);
  lines.push('');

  // Links line
  const linkParts: string[] = [];
  linkParts.push(`[GitHub](${palletLinks.github})`);
  if (palletLinks.docsRs) {
    linkParts.push(`[docs.rs](${palletLinks.docsRs})`);
  }
  if (palletLinks.cratesIo) {
    linkParts.push(`[crates.io](${palletLinks.cratesIo})`);
  }
  linkParts.push(`[Subscan](${subscanLink})`);
  lines.push(linkParts.join(' · '));
  lines.push('');

  // Storage section with Rust code blocks
  if (detailed && detailed.storage.length > 0) {
    lines.push(`## Storage (${storageCount})`);
    lines.push('');
    for (const storage of detailed.storage) {
      const rustType = formatRustType(storage.type);
      const docs = cleanDocs(storage.docs);
      lines.push(`### ${storage.name}`);
      lines.push('');
      if (docs) {
        lines.push(docs);
        lines.push('');
      }
      lines.push('```rust');
      lines.push(`${storage.name}: ${rustType}`);
      lines.push('```');
      lines.push('');

      // Show SDK methods that read this storage - with links to SDK docs
      const storageKey = `${pallet.name.toLowerCase()}.${storage.name.toLowerCase()}`;
      const sdkMethods = storageToSDK.get(storageKey);
      if (sdkMethods && sdkMethods.length > 0) {
        // Create linked method names: [ClassName.method](/reference/sdk/package#classname)
        const linkedMethods = sdkMethods.map(m => {
          const className = m.method.includes('.') ? m.method.split('.')[0] : '';
          const anchor = className ? `#${className.toLowerCase()}` : '';
          return `[${m.method}](/reference/sdk/${m.package}${anchor})`;
        });
        lines.push(`**Read by SDK:** ${linkedMethods.join(', ')}`);
        lines.push('');
      }
    }
  } else if (pallet.storage.length > 0) {
    lines.push(`## Storage (${storageCount})`);
    lines.push('');
    lines.push('```rust');
    for (const storage of pallet.storage) {
      const name = storage.replace(`${pallet.name}.`, '');
      lines.push(name);
    }
    lines.push('```');
    lines.push('');
  }

  // Calls (Extrinsics) section with Rust signatures
  if (detailed && detailed.calls.length > 0) {
    const realCalls = detailed.calls.filter(c => !c.name.startsWith('__Unused'));
    if (realCalls.length > 0) {
      lines.push(`## Extrinsics (${callsCount})`);
      lines.push('');
      for (const call of realCalls) {
        const docs = cleanDocs(call.docs);
        lines.push(`### ${call.name}`);
        lines.push('');
        if (docs) {
          lines.push(docs);
          lines.push('');
        }
        lines.push('```rust');
        if (call.args.length === 0) {
          lines.push(`fn ${call.name}(origin: OriginFor<T>)`);
        } else {
          lines.push(`fn ${call.name}(`);
          lines.push('    origin: OriginFor<T>,');
          for (const arg of call.args) {
            lines.push(`    ${arg.name}: ${arg.type},`);
          }
          lines.push(')');
        }
        lines.push('```');
        lines.push('');
      }
    }
  } else if (pallet.calls.length > 0) {
    lines.push(`## Extrinsics (${callsCount})`);
    lines.push('');
    lines.push('```rust');
    for (const call of pallet.calls) {
      const name = call.replace(`${pallet.name}.`, '');
      lines.push(`fn ${name}(origin: OriginFor<T>, ...)`);
    }
    lines.push('```');
    lines.push('');
  }

  // Events section with Rust structs
  if (detailed && detailed.events.length > 0) {
    lines.push(`## Events (${eventsCount})`);
    lines.push('');
    for (const event of detailed.events) {
      const docs = cleanDocs(event.docs);
      lines.push(`### ${event.name}`);
      lines.push('');
      if (docs) {
        lines.push(docs);
        lines.push('');
      }
      if (event.fields.length > 0) {
        lines.push('```rust');
        lines.push(`${event.name} {`);
        for (const field of event.fields) {
          if (field.name) {
            lines.push(`    ${field.name}: ${field.type},`);
          } else {
            lines.push(`    ${field.type},`);
          }
        }
        lines.push('}');
        lines.push('```');
      } else {
        lines.push('```rust');
        lines.push(`${event.name}`);
        lines.push('```');
      }
      // Add indexer handler link if this event is indexed
      const fullEventName = `${pallet.name}.${event.name}`;
      const eventMapping = eventToHandlerMap?.[fullEventName];
      if (eventMapping && eventMapping.entities.length > 0) {
        // Filter to only valid entity names (not enum types)
        const validEntities = validEntityNames?.size
          ? eventMapping.entities.filter(e => validEntityNames.has(e))
          : eventMapping.entities;
        if (validEntities.length > 0) {
          lines.push('');
          const entityLinks = validEntities.map(e => `[${e}](/reference/indexer/${e})`).join(', ');
          lines.push(`**Indexed by:** ${entityLinks}`);
        }
      }
      lines.push('');
    }
  } else if (pallet.events.length > 0) {
    lines.push(`## Events (${eventsCount})`);
    lines.push('');
    lines.push('```rust');
    for (const event of pallet.events) {
      const name = event.replace(`${pallet.name}.`, '');
      lines.push(name);
    }
    lines.push('```');
    lines.push('');
  }

  // Constants section with Rust code blocks
  if (detailed && detailed.constants.length > 0) {
    lines.push(`## Constants (${constantsCount})`);
    lines.push('');
    for (const constant of detailed.constants) {
      const docs = cleanDocs(constant.docs);
      lines.push(`### ${constant.name}`);
      lines.push('');
      if (docs) {
        lines.push(docs);
        lines.push('');
      }
      lines.push('```rust');
      lines.push(`const ${constant.name}: ${constant.type}`);
      lines.push('```');
      lines.push('');
    }
  } else if (pallet.constants.length > 0) {
    lines.push(`## Constants (${constantsCount})`);
    lines.push('');
    lines.push('```rust');
    for (const constant of pallet.constants) {
      const name = constant.replace(`${pallet.name}.`, '');
      lines.push(`const ${name}`);
    }
    lines.push('```');
    lines.push('');
  }

  // References section (cross-references to other layers)
  if (entities.length > 0 || hooks.length > 0 || sdkRefs.length > 0) {
    lines.push(`## References`);
    lines.push('');

    // SDK packages that use this pallet
    if (sdkRefs.length > 0) {
      // Get unique packages
      const uniquePackages = [...new Set(sdkRefs.map(r => r.package))];
      lines.push(`### SDK (${uniquePackages.length})`);
      lines.push('');
      for (const pkg of uniquePackages) {
        lines.push(`- [${pkg}](/reference/sdk/${pkg})`);
      }
      lines.push('');
    }

    // Indexer entities
    if (entities.length > 0) {
      // Separate entities from handlers
      const regularEntities = entities.filter(e => !e.startsWith('handler:'));

      if (regularEntities.length > 0) {
        lines.push(`### Indexer (${regularEntities.length})`);
        lines.push('');
        for (const entity of regularEntities) {
          lines.push(`- [${entity}](/reference/indexer/${entity})`);
        }
        lines.push('');
      }
    }

    // UI hooks
    if (hooks.length > 0) {
      lines.push(`### UI (${hooks.length})`);
      lines.push('');
      for (const hook of hooks) {
        lines.push(`- [${hook.name}](/reference/hooks/${hook.category}/${hook.name})`);
      }
      lines.push('');
    }
  }

  return lines.join('\n');
}

function generatePalletsIndex(
  metadata: ChainMetadata,
  pallets: PalletMetadata[],
  palletToHooks: Map<string, { name: string; category: string }[]>
): string {
  const lines: string[] = [
    '---',
    'title: Runtime Reference',
    'description: Complete reference for all Substrate runtime pallets',
    'sidebar_class_name: hidden',
    '---',
    '',
    '# Runtime Reference',
    '',
    `Substrate runtime pallets · ${metadata.specName} v${metadata.specVersion} · ${pallets.length} pallets`,
    '',
  ];

  // List all pallets sorted by index
  for (const pallet of pallets) {
    const hooks = palletToHooks.get(pallet.name.toLowerCase()) || [];
    const hooksInfo = hooks.length > 0 ? ` · ${hooks.length} UI` : '';
    lines.push(`- [${pallet.name}](/reference/pallets/${pallet.name}) (#${pallet.index})${hooksInfo}`);
  }

  lines.push('');

  return lines.join('\n');
}

// Version manifest structure for tracking and diff detection
interface VersionManifest {
  generatedAt: string;
  specName: string;
  specVersion: number;
  blockNumber: number;
  // All dependency sources by repo
  sources: {
    [repo: string]: {
      label: string;
      branch: string;
      commit: string;
      forkRepo?: string;
    };
  };
  // All pallets with their version info
  pallets: {
    name: string;
    index: number;
    origin: string;
    crateName?: string;
    version?: string;
    commit?: string;
    branch?: string;
    forkRepo?: string;
    // Counts for diff detection
    storageCount: number;
    callsCount: number;
    eventsCount: number;
    constantsCount: number;
  }[];
}

// Generate a version manifest for tracking and comparison
function generateVersionManifest(
  metadata: ChainMetadata,
  pallets: PalletMetadata[]
): VersionManifest {
  const allDeps = parseAllCargoLockDependencies();

  // Collect unique sources (repos)
  const sources: VersionManifest['sources'] = {};

  // Add HydraDX-node source first (the main runtime repo)
  const hydradxInfo = getHydradxGitInfo();
  sources['galacticcouncil/HydraDX-node'] = {
    label: 'HydraDX',
    branch: hydradxInfo.branch,
    commit: hydradxInfo.commit,
  };

  // Add external dependency sources from Cargo.lock
  for (const dep of allDeps.values()) {
    if (dep.sourceType !== 'git' || !dep.repo) continue;

    const repoKey = dep.repo;
    if (!sources[repoKey] && dep.commit) {
      const config = KNOWN_REPOS[dep.forkRepo || dep.repo];
      sources[repoKey] = {
        label: config?.label || dep.repo.split('/')[1] || dep.repo,
        branch: dep.branch || 'main',
        commit: dep.commit,
        forkRepo: dep.forkRepo !== dep.repo ? dep.forkRepo : undefined,
      };
    }
  }

  // Build pallet version info
  const palletInfos: VersionManifest['pallets'] = pallets.map(pallet => {
    const links = buildPalletLinks(pallet.name);
    const sourceLabel = getSourceLabel(pallet.name);
    const source = getPalletSource(pallet.name);

    return {
      name: pallet.name,
      index: pallet.index,
      origin: sourceLabel,
      crateName: source.crateName,
      version: links.version,
      commit: links.commit,
      branch: links.branch,
      forkRepo: links.forkRepo,
      storageCount: pallet.storage.length,
      callsCount: pallet.calls.length,
      eventsCount: pallet.events.length,
      constantsCount: pallet.constants.length,
    };
  });

  return {
    generatedAt: new Date().toISOString(),
    specName: metadata.specName,
    specVersion: metadata.specVersion,
    blockNumber: metadata.blockNumber,
    sources,
    pallets: palletInfos,
  };
}

// CLI
if (import.meta.url === `file://${process.argv[1]}`) {
  const extractionsPath = process.env.EXTRACTIONS_PATH || './raw';
  const outputPath = process.env.OUTPUT_PATH || './docs-site/docs';

  synthesizePallets({
    extractionsPath,
    outputPath,
  }).catch((err) => {
    console.error('Pallet generation failed:', err);
    process.exit(1);
  });
}
