import { join } from 'path';
import { format } from 'date-fns';
import { createLogger } from '../utils/logger.js';
import { readJSON, writeFile } from '../utils/files.js';
import type { Proposal, ProposalDocument } from '../schemas/proposals.js';

const log = createLogger('propose');

interface SynthesisResult {
  synthesizedAt: string;
  discrepancies: Array<{
    id: string;
    severity: 'critical' | 'warning' | 'info';
    type: string;
    description: string;
    layers: string[];
    details: Record<string, unknown>;
  }>;
}

function discrepancyToProposal(d: SynthesisResult['discrepancies'][0]): Proposal {
  const severityMap = {
    critical: 'critical' as const,
    warning: 'recommended' as const,
    info: 'minor' as const,
  };

  const repoMap: Record<string, string> = {
    missing_sdk_wrapper: 'galacticcouncil/sdk',
    unindexed_event: 'galacticcouncil/hydration-data-lake',
    direct_sdk_usage: 'galacticcouncil/hydration-ui',
  };

  return {
    id: d.id,
    severity: severityMap[d.severity],
    title: d.description,
    repo: repoMap[d.type] || 'unknown',
    type: d.type as Proposal['type'],
    problem: d.description,
    fix: generateFix(d),
    files: [],
    impact: d.severity === 'critical' ? 'Breaking change if not addressed' : undefined,
    detectedBy: 'lead-architect',
    detectedAt: new Date().toISOString(),
  };
}

function generateFix(d: SynthesisResult['discrepancies'][0]): string {
  switch (d.type) {
    case 'missing_sdk_wrapper':
      return `Add SDK method to expose ${d.details.pallet}.${d.details.extrinsic}`;
    case 'unindexed_event':
      return `Add Subsquid handler for ${d.details.pallet}.${d.details.event}`;
    case 'direct_sdk_usage':
      return 'Consider abstracting SDK calls into reusable hooks';
    default:
      return 'Manual review required';
  }
}

function generateMarkdown(doc: ProposalDocument): string {
  let md = `# Change Proposals - ${format(new Date(doc.generatedAt), 'yyyy-MM-dd')}

> Generated by: Lead Architect
> Generated at: ${doc.generatedAt}

## Summary

| Severity | Count |
|----------|-------|
| Critical | ${doc.summary.critical} |
| Recommended | ${doc.summary.recommended} |
| Minor | ${doc.summary.minor} |

---

`;

  const critical = doc.proposals.filter(p => p.severity === 'critical');
  const recommended = doc.proposals.filter(p => p.severity === 'recommended');
  const minor = doc.proposals.filter(p => p.severity === 'minor');

  if (critical.length > 0) {
    md += `## Critical\n\n`;
    for (const p of critical) {
      md += `### [${p.id}] ${p.title}\n\n`;
      md += `**Repo:** ${p.repo}\n`;
      md += `**Type:** ${p.type}\n\n`;
      md += `**Problem:** ${p.problem}\n\n`;
      md += `**Fix:** ${p.fix}\n\n`;
      if (p.impact) md += `**Impact:** ${p.impact}\n\n`;
      md += `---\n\n`;
    }
  }

  if (recommended.length > 0) {
    md += `## Recommended\n\n`;
    for (const p of recommended) {
      md += `### [${p.id}] ${p.title}\n\n`;
      md += `**Repo:** ${p.repo}\n`;
      md += `**Fix:** ${p.fix}\n\n`;
      md += `---\n\n`;
    }
  }

  if (minor.length > 0) {
    md += `## Minor\n\n`;
    for (const p of minor) {
      md += `- **[${p.id}]** ${p.title} - ${p.fix}\n`;
    }
    md += '\n';
  }

  md += `---

## Human Review Checklist

`;

  for (const p of doc.proposals) {
    md += `- [ ] **${p.id}**: Approved / Rejected / Needs Discussion\n`;
  }

  md += `
---

## Approved Changes Log

| ID | Status | PR/Issue | Notes |
|----|--------|----------|-------|
`;

  for (const p of doc.proposals) {
    md += `| ${p.id} | Pending | - | - |\n`;
  }

  return md;
}

export async function generateProposals(
  synthesisPath: string,
  outputPath: string
): Promise<ProposalDocument> {
  log.section('Hydration Codex - Proposal Generation');
  log.info(`Input: ${synthesisPath}`);
  log.info(`Output: ${outputPath}`);

  const synthesis = readJSON<SynthesisResult>(join(synthesisPath, 'synthesis.json'));
  if (!synthesis) {
    throw new Error('Missing synthesis.json. Run synthesis first.');
  }

  log.section('Converting Discrepancies to Proposals');
  const proposals = synthesis.discrepancies.map(discrepancyToProposal);
  log.success(`Generated ${proposals.length} proposals`);

  const doc: ProposalDocument = {
    generatedAt: new Date().toISOString(),
    generatedBy: 'lead-architect',
    summary: {
      critical: proposals.filter(p => p.severity === 'critical').length,
      recommended: proposals.filter(p => p.severity === 'recommended').length,
      minor: proposals.filter(p => p.severity === 'minor').length,
    },
    proposals,
  };

  // Write JSON
  const dateStr = format(new Date(), 'yyyy-MM-dd');
  const jsonPath = join(outputPath, `${dateStr}-proposals.json`);
  writeFile(jsonPath, JSON.stringify(doc, null, 2));
  log.success(`Wrote ${jsonPath}`);

  // Write Markdown
  const mdPath = join(outputPath, `${dateStr}-proposals.md`);
  writeFile(mdPath, generateMarkdown(doc));
  log.success(`Wrote ${mdPath}`);

  log.section('Proposal Generation Complete');
  console.log(`
  Critical:    ${doc.summary.critical}
  Recommended: ${doc.summary.recommended}
  Minor:       ${doc.summary.minor}
  Total:       ${proposals.length}
  `);

  return doc;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const synthesisPath = process.env.SYNTHESIS_PATH || './docs';
  const outputPath = process.env.OUTPUT_PATH || './proposals';

  generateProposals(synthesisPath, outputPath).catch((err) => {
    console.error('Proposal generation failed:', err);
    process.exit(1);
  });
}
